#!/bin/bash
# CECE-ASCII v1.0 - ASCII Art Library
blackroad() {
    echo "    ____  __    ___   ________ __ ____  ____  ___    ____ "
    echo "   / __ )/ /   /   | / ____/ //_// __ \/ __ \/   |  / __ \\"
    echo "  / __  / /   / /| |/ /   / ,<  / /_/ / / / / /| | / / / /"
    echo " / /_/ / /___/ ___ / /___/ /| |/ _, _/ /_/ / ___ |/ /_/ / "
    echo "/_____/_____/_/  |_\____/_/ |_/_/ |_|\____/_/  |_/_____/  "
}
cece() {
    echo "   ______ _______ ______ _______ "
    echo "  / ____// ____/ / ____// ____/ "
    echo " / /    / __/   / /    / __/    "
    echo "/ /___ / /___  / /___ / /___    "
    echo "\____//_____/  \____//_____/    "
}
heart() {
    echo "  ♥♥♥     ♥♥♥  "
    echo " ♥   ♥   ♥   ♥ "
    echo "♥     ♥ ♥     ♥"
    echo " ♥    ♥♥♥    ♥ "
    echo "  ♥   ♥♥♥   ♥  "
    echo "   ♥  ♥♥♥  ♥   "
    echo "    ♥ ♥♥♥ ♥    "
    echo "     ♥♥♥♥♥     "
}
case "$1" in
    blackroad) blackroad ;;
    cece) cece ;;
    heart) heart ;;
    *) echo "CECE-ASCII: blackroad | cece | heart" ;;
esac
