#!/bin/bash
# CECE-PASSWORD v1.0 - Password Generator
generate() {
    LENGTH="${1:-16}"
    CHARS='A-Za-z0-9!@#$%^&*'
    PASSWORD=$(LC_ALL=C tr -dc "$CHARS" < /dev/urandom | head -c "$LENGTH")
    echo "$PASSWORD"
}

memorable() {
    WORDS=("black" "road" "quantum" "cosmic" "stellar" "nova" "cyber" "pixel" "neon" "prime" "omega" "alpha" "delta" "echo" "sigma")
    W1=${WORDS[$RANDOM % ${#WORDS[@]}]}
    W2=${WORDS[$RANDOM % ${#WORDS[@]}]}
    NUM=$((RANDOM % 999))
    echo "${W1^}${W2^}${NUM}!"
}

check_strength() {
    PASS="$1"
    LEN=${#PASS}
    SCORE=0
    [ $LEN -ge 8 ] && ((SCORE++))
    [ $LEN -ge 12 ] && ((SCORE++))
    [[ "$PASS" =~ [A-Z] ]] && ((SCORE++))
    [[ "$PASS" =~ [a-z] ]] && ((SCORE++))
    [[ "$PASS" =~ [0-9] ]] && ((SCORE++))
    [[ "$PASS" =~ [^A-Za-z0-9] ]] && ((SCORE++))
    
    case $SCORE in
        0|1|2) echo "Weak" ;;
        3|4) echo "Medium" ;;
        5|6) echo "Strong" ;;
    esac
}

case "$1" in
    generate) generate "$2" ;;
    memorable) memorable ;;
    check) check_strength "$2" ;;
    *) echo "CECE-PASSWORD: generate [length] | memorable | check <password>" ;;
esac
