#!/bin/bash
# CECE-NPM v1.0 - NPM Helper
init() { npm init -y; }
install() { npm install "$1"; }
run() { npm run "$1"; }
outdated() { npm outdated; }
audit() { npm audit; }
case "$1" in
    init) init ;;
    install) install "$2" ;;
    run) run "$2" ;;
    outdated) outdated ;;
    audit) audit ;;
    *) echo "CECE-NPM: init | install <pkg> | run <script> | outdated | audit" ;;
esac
