#!/bin/bash
# CECE-GCLOUD v1.0 - GCloud Helper
projects() { gcloud projects list; }
instances() { gcloud compute instances list; }
functions() { gcloud functions list; }
case "$1" in
    projects) projects ;;
    instances) instances ;;
    functions) functions ;;
    *) echo "CECE-GCLOUD: projects | instances | functions" ;;
esac
