#!/bin/bash
# CECE-TERRAFORM v1.0 - Terraform Helper
init() { terraform init; }
plan() { terraform plan; }
apply() { terraform apply -auto-approve; }
destroy() { terraform destroy -auto-approve; }
case "$1" in
    init) init ;;
    plan) plan ;;
    apply) apply ;;
    destroy) destroy ;;
    *) echo "CECE-TERRAFORM: init | plan | apply | destroy" ;;
esac
