#!/bin/bash
# CECE-QUOTE v1.0 - Quote Generator
QUOTES=(
"The only way to do great work is to love what you do. - Steve Jobs"
"Innovation distinguishes between a leader and a follower. - Steve Jobs"
"Stay hungry, stay foolish. - Steve Jobs"
"Move fast and break things. - Mark Zuckerberg"
"The road remembers everything. - BlackRoad"
"Sovereignty over dependency. - CECE"
"Code is poetry. - WordPress"
"Talk is cheap. Show me the code. - Linus Torvalds"
"First, solve the problem. Then, write the code. - John Johnson"
"Any fool can write code that a computer can understand. - Martin Fowler"
)

random_quote() {
    echo "${QUOTES[$RANDOM % ${#QUOTES[@]}]}"
}

case "$1" in
    random) random_quote ;;
    *) random_quote ;;
esac
